### ISSUE TITLE
Task bar play button does nothing for the GMusic app in Ubuntu 16.04

### ISSUE THREAD

**Issue by moorepants** [tiliado/nuvola-app-google-play-music#12] opened 2016-05-19 16:12 UTC
I would expect to be able to pause and play from the sound menu in Ubuntu for the G Music app in Nuvola, but it doesn't do anything when pressed. It simply stays fixed as a play arrow.

Nuvola: 3.0.2
Google Play Music: 5.13

**Comment by fenryxo** [comment] 2016-05-20 11:03
Hello @moorepants. Your issue is a duplicate of tiliado/nuvolaplayer#224.

The issue has been fixed in the git master branch and in the packages of Nuvola Player 3.1 Rolling Releases. Later, the fix will be also included in an upcoming Nuvola Player 3.0.3 Stable Release next month unless a regression is found.

**Closed by fenryxo** 2016-05-20 11:03 UTC
