### ISSUE TITLE
Can't scroll through playlist

### ISSUE THREAD

**Issue by DavidDohmen** [tiliado/nuvola-app-google-play-music#10] opened 2016-02-03 01:21 UTC
I can scroll through the main screen, but when I open the playlist it doesn't get it's own scrollbar and the biggest part of the playlist is outside of the window and can't be reached. 
![image](https://cloud.githubusercontent.com/assets/6106225/12769979/b5247506-ca1c-11e5-90bf-ffc965dfd454.png)

OS: elementary (based on Ubuntu 14.04).

**Comment by fenryxo** [comment] 2016-02-03 13:08
Hello. Thanks for reporting this issue. Is it also reproducible in the [WebKitGtk MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?

**Comment by iddqdidkfa** [comment] 2016-02-09 16:51
I can confirm that this bugreproducable in WebKitGtk MiniBrowser.
And Google Play music also stucks in that browser after some time (~5 minutes) like In Nuvola Player app.

**Comment by fenryxo** [comment] 2016-02-10 10:43
Hello. Since the issue is reproducible also in the WebKitGtk 2.4.8 MiniBrowser and I cannot reproduce it with a newer WebKitGtk (2.6.2 in Debian Jessie), I believe Google Play Music simply requires a newer WebKitGTK than 2.4.8 available in Ubuntu 14.04/elementary OS Freya.

I've added a new entry to Known issues ([Scrolling through the playlist queue doesn't work with WebKitGtk 2.4.8](https://github.com/tiliado/nuvola-app-google-play-music/wiki/Known-Issues#scrolling-through-the-playlist-queue-doesnt-work-with-webkitgtk-248)) and I'm closing this ticket as an upstream issue. I'm sorry I cannot do more.

**Closed by fenryxo** 2016-02-10 10:43 UTC
Labels: bug, upstream

**Comment by iddqdidkfa** [comment] 2016-02-19 14:06
I have updated webkitgtk and nuvaola player and now everything works fine (On elementary OS Freya 0.3.1).
